### ISSUE TITLE
Just curious - why this interpreter?

### ISSUE THREAD

**Issue by dumblob** [Delta456/monkey_v#3]
I'm a bit language (incl. programming langs :wink:) freak and I'm curious what was your motivation to implement this language?

**Comment by Delta456** [comment]
I wanted to learn how to make and understand a compiler and interpreter works. As I learn and code I wanted to make one in V because it will fun.

**Comment by dumblob** [comment]
Oh, if that's the reason, then there is the ultimate king of "languages" - AST. Yes, it's the abstract syntax tree itself. Having a language which is at the same time an AST offers by definition the biggest power possible, but at the same time the most concise (i.e. understandable and with proper syntax also well readable) description of algorithms, patterns, data, ... the world around us.

There are at least these languages building upon this principle I know of.

1. [Tcl](https://www.tcl.tk/ ) (the syntax is though not very well chosen - everything being a string all the time does make things more verbose than necessary, less readable and less efficient)
1. [Rebol](https://github.com/rebol/rebol ) (the first "seamless" take on on this approach - taking homoiconicity to a whole new level compared to Tcl)
2. [Red](https://www.red-lang.org/ ) (modern successor of Rebol - worth looking at because of its sublanguage "Red/System" being as performant as C)
3. [Spry](http://sprylang.se/manual.html ) (very new take on on the approach - follows the KISS principle everywhere, smoothing most of the sharper edges of Rebol and Red)

I personally think, that the first three are somewhat less elegant than the fourth. I think it would be super cool to have a *V* implementation of Spry. It should fit under few hundred lines of code and with some "standard library" and "accelerated functions" (i.e. implemented natively in *V* rather than in Spry itself) under 2000 lines of code. Currently there is only Spry virtual machine written in Nim if I'm not mistaken.

Btw. Tcl and Rebol are being used in millions of applications from different segments (avionics, SCADA, graphics, CAD, testing, ...) which renders this "live AST" concept very successful with bright future, though still nearly unexplored.

**Comment by Delta456** [comment]
Hmm. Will see when I will do it. Thanks for linking me up with the links!

**Comment by dumblob** [comment]
If you ever decided to dive into the world of "live abstract syntax trees", then you'll need a mutable tree structure which is [cache oblivious](https://en.wikipedia.org/wiki/Cache-oblivious_algorithm ) (or you'll end up with a very slow runtime). Currently the state of the art is [MinWEP](https://arxiv.org/abs/1307.5899 ). Naive pointer-based trees or the good old B-trees are by far insufficient nowadays ([here is why](https://github.com/rcoh/treelayout )).

**Comment by Delta456** [comment]
I see thanks
